package com.example.springproject.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

@Entity
public class Message {
    @Column (name="message_id")
    @Id @GeneratedValue
    private Integer message_id;
    /**
     * id for the message posted by a specific user. Let's assume it is posted by
     * the front end
     */
    @Column (name="posted_by")
    private Integer posted_by;

    /**
     * text for the message.It should not be blank
     */
    @Column (name="message_text")
    private String message_text;

    /**
     * the epoch time is when this tweet was posted. Assume it is provided by the front end
     */
    @Column (name="time_posted_epoch")
    private Long time_posted_epoch;

    /**
     * default no-args constructor
     */
    public Message() {
    }

    /**
     * when posting a new message, the id is generated by the database
     * @param messageText
     * @param postedBy
     * @param timePostedEpoch
    */
    public Message(String message_text, Integer posted_by, Long time_posted_epoch) {
        this.message_text = message_text;
        this.posted_by = posted_by;
        this.time_posted_epoch = time_posted_epoch;
    }
    
    /**
     * when retrieving message from the database all fields are neccessary
     * @param message_id
     * @param message_text
     * @param posted_by
     * @param time_posted_epoch
     */
    public Message(Integer message_id, String message_text, Integer posted_by, Long time_posted_epoch) {
        this.message_id = message_id;
        this.message_text = message_text;
        this.posted_by = posted_by;
        this.time_posted_epoch = time_posted_epoch;
    }


    /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @returrn message_id
     */
    public Integer getMessageId() {
        return message_id;
    }

    /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @param message_id
     */
    public void setMessageId(Integer message_id) {
        this.message_id = message_id;
    }

    /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @return postedBy
     */

    public Integer getPostedBy() {
        return posted_by;
    }

    /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @param postedBy
     */
    public void setPostedBy(Integer posted_by) {
        this.posted_by = posted_by;
    }

      /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @return messageText
     */
    public String getMessageText() {
        return message_text;
    }

    /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @param messageText
     */
    public void setMessageText(String message_text) {
        this.message_text = message_text;
    }

    /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @return timePostedEpoch
     */
    public Long getTimePostedEpoch() {
        return time_posted_epoch;
    }

    /**
     * getters and setters are needed for Jackson ObjectMapper to work
     * @param timePostedEpoch
     */
    public void setTimePostedEpoch(Long time_posted_epoch) {
        this.time_posted_epoch = time_posted_epoch;
    }  

}
